# Generated by Django 3.0.7 on 2021-01-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20210111_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractdetail',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractdetail',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contractdetail',
            name='qtty',
            field=models.FloatField(),
        ),
    ]
