# Generated by Django 3.0.7 on 2021-01-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20210111_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetail',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
