# Generated by Django 3.0.7 on 2021-01-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20210111_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetail',
            name='qtty',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
        migrations.AlterField(
            model_name='contractdetail',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
