# Generated by Django 3.0.7 on 2021-01-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_auto_20210111_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetail',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctr_details', to='contracts.Contract'),
        ),
    ]
